<template>
    <div>
      <p>Welcome to Step 1! Here you can enter some basic information.</p>
  
      <!-- 创建一些文本和输入框以增加内容长度 -->
      <v-text-field label="Your Name" outlined></v-text-field>
      <v-text-field label="Your Email" outlined></v-text-field>
      <v-text-field label="Phone Number" outlined></v-text-field>
      <v-text-field label="Address" outlined></v-text-field>
      <v-text-field label="City" outlined></v-text-field>
      <v-text-field label="State" outlined></v-text-field>
      <v-text-field label="Postal Code" outlined></v-text-field>
      <v-text-field label="Country" outlined></v-text-field>
  
      <p>Some more content below to test the scrolling behavior:</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia dolor vel arcu volutpat, a cursus tortor sollicitudin. Nam fringilla, urna et vulputate volutpat, libero odio feugiat ipsum, eget egestas nunc urna sed risus. Fusce vehicula ut felis eu gravida. Morbi efficitur urna ac risus volutpat, nec volutpat erat vehicula. Integer interdum euismod purus, et efficitur felis efficitur sed. Donec suscipit, ante id volutpat tristique, sem arcu ultricies turpis, a cursus lorem eros vitae eros. Sed nec lorem et lorem viverra suscipit.</p>
      <p>Curabitur et velit at libero faucibus sodales eget sed nisi. Donec a libero est. Proin placerat laoreet arcu, ac convallis lorem dictum vel. Nulla facilisi. Curabitur ullamcorper vestibulum ante, in efficitur enim interdum sed. Quisque id massa nec nisi accumsan auctor. Integer faucibus neque et magna sollicitudin tincidunt. Nulla facilisi. Ut nec velit sem. Donec in lobortis ligula. Donec bibendum, libero ac cursus mollis, eros libero sollicitudin sapien, in consequat eros metus non ligula.</p>
      <p>Nulla vel erat eu urna sodales mollis vel vel dui. Pellentesque dapibus velit ut velit scelerisque tincidunt. Integer eget urna ut sapien bibendum laoreet a at purus. Nunc nec erat malesuada, ullamcorper nulla eu, eleifend velit. Aliquam tincidunt nisi augue, vitae ultricies elit ultricies at. Suspendisse potenti. Vivamus fermentum, elit in faucibus tincidunt, libero metus posuere erat, sed consectetur lorem risus eget turpis. Integer lacinia nulla vel leo pharetra malesuada. Proin nec convallis neque.</p>
  
      <p>More dummy text to ensure long content:</p>
      <p>Curabitur euismod turpis non venenatis pharetra. Ut pharetra dolor ut nisi interdum auctor. Phasellus vulputate felis ac sapien tempus viverra. Sed et eros ac turpis placerat dignissim vel vel turpis. Sed scelerisque, mauris ac fermentum fermentum, elit sapien cursus orci, ac cursus tortor turpis ut felis. Etiam eu gravida sem. Aenean malesuada ligula vitae diam volutpat, at gravida dui tristique. Cras ut erat eu ipsum ultricies tempor at id tortor. Duis hendrerit urna dui, in malesuada est faucibus vel.</p>
      <p>Praesent congue, orci vel hendrerit consequat, odio arcu consectetur orci, eget consequat odio metus eu augue. Vestibulum euismod consequat odio, sit amet aliquet enim. Nam luctus laoreet orci, vitae iaculis eros interdum sit amet. Fusce eu magna elit. Etiam eget magna feugiat, scelerisque ipsum et, porttitor ante. Aenean ut cursus est. Fusce vehicula consectetur velit. Proin sed felis non purus feugiat condimentum. Sed scelerisque justo non urna malesuada, vitae pretium justo accumsan.</p>
  
      <p>That's all! You've completed Step 1.</p>
      <p>Some more content below to test the scrolling behavior:</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia dolor vel arcu volutpat, a cursus tortor sollicitudin. Nam fringilla, urna et vulputate volutpat, libero odio feugiat ipsum, eget egestas nunc urna sed risus. Fusce vehicula ut felis eu gravida. Morbi efficitur urna ac risus volutpat, nec volutpat erat vehicula. Integer interdum euismod purus, et efficitur felis efficitur sed. Donec suscipit, ante id volutpat tristique, sem arcu ultricies turpis, a cursus lorem eros vitae eros. Sed nec lorem et lorem viverra suscipit.</p>
      <p>Curabitur et velit at libero faucibus sodales eget sed nisi. Donec a libero est. Proin placerat laoreet arcu, ac convallis lorem dictum vel. Nulla facilisi. Curabitur ullamcorper vestibulum ante, in efficitur enim interdum sed. Quisque id massa nec nisi accumsan auctor. Integer faucibus neque et magna sollicitudin tincidunt. Nulla facilisi. Ut nec velit sem. Donec in lobortis ligula. Donec bibendum, libero ac cursus mollis, eros libero sollicitudin sapien, in consequat eros metus non ligula.</p>
      <p>Nulla vel erat eu urna sodales mollis vel vel dui. Pellentesque dapibus velit ut velit scelerisque tincidunt. Integer eget urna ut sapien bibendum laoreet a at purus. Nunc nec erat malesuada, ullamcorper nulla eu, eleifend velit. Aliquam tincidunt nisi augue, vitae ultricies elit ultricies at. Suspendisse potenti. Vivamus fermentum, elit in faucibus tincidunt, libero metus posuere erat, sed consectetur lorem risus eget turpis. Integer lacinia nulla vel leo pharetra malesuada. Proin nec convallis neque.</p>
  
      <p>More dummy text to ensure long content:</p>
      <p>Curabitur euismod turpis non venenatis pharetra. Ut pharetra dolor ut nisi interdum auctor. Phasellus vulputate felis ac sapien tempus viverra. Sed et eros ac turpis placerat dignissim vel vel turpis. Sed scelerisque, mauris ac fermentum fermentum, elit sapien cursus orci, ac cursus tortor turpis ut felis. Etiam eu gravida sem. Aenean malesuada ligula vitae diam volutpat, at gravida dui tristique. Cras ut erat eu ipsum ultricies tempor at id tortor. Duis hendrerit urna dui, in malesuada est faucibus vel.</p>
      <p>Praesent congue, orci vel hendrerit consequat, odio arcu consectetur orci, eget consequat odio metus eu augue. Vestibulum euismod consequat odio, sit amet aliquet enim. Nam luctus laoreet orci, vitae iaculis eros interdum sit amet. Fusce eu magna elit. Etiam eget magna feugiat, scelerisque ipsum et, porttitor ante. Aenean ut cursus est. Fusce vehicula consectetur velit. Proin sed felis non purus feugiat condimentum. Sed scelerisque justo non urna malesuada, vitae pretium justo accumsan.</p>
  
      <p>That's all! You've completed Step 1.</p>
      <p>Some more content below to test the scrolling behavior:</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia dolor vel arcu volutpat, a cursus tortor sollicitudin. Nam fringilla, urna et vulputate volutpat, libero odio feugiat ipsum, eget egestas nunc urna sed risus. Fusce vehicula ut felis eu gravida. Morbi efficitur urna ac risus volutpat, nec volutpat erat vehicula. Integer interdum euismod purus, et efficitur felis efficitur sed. Donec suscipit, ante id volutpat tristique, sem arcu ultricies turpis, a cursus lorem eros vitae eros. Sed nec lorem et lorem viverra suscipit.</p>
      <p>Curabitur et velit at libero faucibus sodales eget sed nisi. Donec a libero est. Proin placerat laoreet arcu, ac convallis lorem dictum vel. Nulla facilisi. Curabitur ullamcorper vestibulum ante, in efficitur enim interdum sed. Quisque id massa nec nisi accumsan auctor. Integer faucibus neque et magna sollicitudin tincidunt. Nulla facilisi. Ut nec velit sem. Donec in lobortis ligula. Donec bibendum, libero ac cursus mollis, eros libero sollicitudin sapien, in consequat eros metus non ligula.</p>
      <p>Nulla vel erat eu urna sodales mollis vel vel dui. Pellentesque dapibus velit ut velit scelerisque tincidunt. Integer eget urna ut sapien bibendum laoreet a at purus. Nunc nec erat malesuada, ullamcorper nulla eu, eleifend velit. Aliquam tincidunt nisi augue, vitae ultricies elit ultricies at. Suspendisse potenti. Vivamus fermentum, elit in faucibus tincidunt, libero metus posuere erat, sed consectetur lorem risus eget turpis. Integer lacinia nulla vel leo pharetra malesuada. Proin nec convallis neque.</p>
  
      <p>More dummy text to ensure long content:</p>
      <p>Curabitur euismod turpis non venenatis pharetra. Ut pharetra dolor ut nisi interdum auctor. Phasellus vulputate felis ac sapien tempus viverra. Sed et eros ac turpis placerat dignissim vel vel turpis. Sed scelerisque, mauris ac fermentum fermentum, elit sapien cursus orci, ac cursus tortor turpis ut felis. Etiam eu gravida sem. Aenean malesuada ligula vitae diam volutpat, at gravida dui tristique. Cras ut erat eu ipsum ultricies tempor at id tortor. Duis hendrerit urna dui, in malesuada est faucibus vel.</p>
      <p>Praesent congue, orci vel hendrerit consequat, odio arcu consectetur orci, eget consequat odio metus eu augue. Vestibulum euismod consequat odio, sit amet aliquet enim. Nam luctus laoreet orci, vitae iaculis eros interdum sit amet. Fusce eu magna elit. Etiam eget magna feugiat, scelerisque ipsum et, porttitor ante. Aenean ut cursus est. Fusce vehicula consectetur velit. Proin sed felis non purus feugiat condimentum. Sed scelerisque justo non urna malesuada, vitae pretium justo accumsan.</p>
  
      <p>That's all! You've completed Step 1.</p>
      <p>Some more content below to test the scrolling behavior:</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia dolor vel arcu volutpat, a cursus tortor sollicitudin. Nam fringilla, urna et vulputate volutpat, libero odio feugiat ipsum, eget egestas nunc urna sed risus. Fusce vehicula ut felis eu gravida. Morbi efficitur urna ac risus volutpat, nec volutpat erat vehicula. Integer interdum euismod purus, et efficitur felis efficitur sed. Donec suscipit, ante id volutpat tristique, sem arcu ultricies turpis, a cursus lorem eros vitae eros. Sed nec lorem et lorem viverra suscipit.</p>
      <p>Curabitur et velit at libero faucibus sodales eget sed nisi. Donec a libero est. Proin placerat laoreet arcu, ac convallis lorem dictum vel. Nulla facilisi. Curabitur ullamcorper vestibulum ante, in efficitur enim interdum sed. Quisque id massa nec nisi accumsan auctor. Integer faucibus neque et magna sollicitudin tincidunt. Nulla facilisi. Ut nec velit sem. Donec in lobortis ligula. Donec bibendum, libero ac cursus mollis, eros libero sollicitudin sapien, in consequat eros metus non ligula.</p>
      <p>Nulla vel erat eu urna sodales mollis vel vel dui. Pellentesque dapibus velit ut velit scelerisque tincidunt. Integer eget urna ut sapien bibendum laoreet a at purus. Nunc nec erat malesuada, ullamcorper nulla eu, eleifend velit. Aliquam tincidunt nisi augue, vitae ultricies elit ultricies at. Suspendisse potenti. Vivamus fermentum, elit in faucibus tincidunt, libero metus posuere erat, sed consectetur lorem risus eget turpis. Integer lacinia nulla vel leo pharetra malesuada. Proin nec convallis neque.</p>
  
      <p>More dummy text to ensure long content:</p>
      <p>Curabitur euismod turpis non venenatis pharetra. Ut pharetra dolor ut nisi interdum auctor. Phasellus vulputate felis ac sapien tempus viverra. Sed et eros ac turpis placerat dignissim vel vel turpis. Sed scelerisque, mauris ac fermentum fermentum, elit sapien cursus orci, ac cursus tortor turpis ut felis. Etiam eu gravida sem. Aenean malesuada ligula vitae diam volutpat, at gravida dui tristique. Cras ut erat eu ipsum ultricies tempor at id tortor. Duis hendrerit urna dui, in malesuada est faucibus vel.</p>
      <p>Praesent congue, orci vel hendrerit consequat, odio arcu consectetur orci, eget consequat odio metus eu augue. Vestibulum euismod consequat odio, sit amet aliquet enim. Nam luctus laoreet orci, vitae iaculis eros interdum sit amet. Fusce eu magna elit. Etiam eget magna feugiat, scelerisque ipsum et, porttitor ante. Aenean ut cursus est. Fusce vehicula consectetur velit. Proin sed felis non purus feugiat condimentum. Sed scelerisque justo non urna malesuada, vitae pretium justo accumsan.</p>
  
      <p>That's all! You've completed Step 1.</p>
    </div>
  </template>
  